export const userConstant = {
    USER_IS_LOGIN: 'USER_IS_LOGIN',
    CHECK_USER_SESSION : 'CHECK_USER_SESSION',
    GOOGLE_SIGN_WITH_START : 'GOOGLE_SIGN_WITH_START',
    EMAIL_SIGN_WITH_START: 'EMAIL_SIGN_WITH_START',
    SIGN_WITH_SUCCESS: 'SIGN_WITH_SUCCESS',
    SIGN_WITH_FAIL: 'SIGN_WITH_FAIL',
    SIGN_UP_START: 'SIGN_UP_START',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_FAIL: 'SIGN_UP_FAIL',
    SIGN_OUT_START: 'SIGN_OUT_START',
    SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
    SIGN_OUT_FAIL: 'SIGN_OUT_FAIL'
}