export const categoriesConstant ={
    FETCH_CATEGORIES_DATA_START:'FETCH_CATEGORIES_DATA_START',
    FETCH_CATEGORIES_DATA_SUCCESS:'FETCH_CATEGORIES_DATA_SUCCESS',
    FETCH_CATEGORIES_DATA_FAIL:'FETCH_CATEGORIES_DATA_FAIL'
}